name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
      - '.github/workflows/**'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt --target ./lambda

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # NOVI KORAK ZA DEBUGIRANJE
      - name: DEBUG - Check AWS Identity and List Functions
        run: |
          echo "--- Checking AWS Identity ---"
          aws sts get-caller-identity
          echo "--- Listing Functions in eu-central-1 ---"
          aws lambda list-functions --region eu-central-1

      - name: Deploy Lambda Function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip